name: Deploy to Netlify

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Ajusta la versión de Node.js según tus necesidades

    - name: Install dependencies
      run: npm install  # O el comando correspondiente si usas otro gestor de paquetes

    - name: Build the project
      run: npm run build  # O el comando correspondiente para construir tu proyecto

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir=build  # Ajusta el directorio si es necesario
